language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - tools
    - build-tools-24.0.1
    - android-24
    - extra-android-support
    - extra-android-m2repository
script: ./gradlew assembleRelease